In [9]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import pycountry
import numpy as np

In [10]:
df = pd.read_excel('ProductionCapa-Company.xlsx', 'years')
df

,Manufacturer,Country,2022 (GWh),2023 (market share),2023 (GWh),2024 (GWh),2025 (GWh),2028 (GWh),2030 (GWh),2035 (GWh),2040 (GWh),2050 (GWh),Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,CATL,China,184.4,0.368,259.7,NaN,NaN,307.0,600.0,NaN,NaN,NaN,NaN,NaN,chrome-extension://efaidnbmnnnibpcajpcglclefin...,https://www.iea.org/reports/global-ev-outlook-...,https://www.catl.com/en/news/1046.html,https://cnevpost.com/2024/02/07/global-ev-batt...
1,CATL,Germany,0.0,NaN,0.0,0.0,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LG Chem,South Corea,NaN,NaN,NaN,NaN,260.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LG Chem,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LG Chem,Poland,NaN,NaN,NaN,65.0,NaN,NaN,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,LG Chem,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,TESLA,United States of America,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,BYD,China,70.5,0.158,111.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Samsung SDI,China,NaN,0.038,NaN,NaN,NaN,94.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Samsung SDI,Hungary,NaN,NaN,NaN,40.0,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Panasonic,Japan,NaN,NaN,NaN,17.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Panasonic,"North America, Mexico",NaN,NaN,NaN,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,SK On,South Corea,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,SK On,Hungary,NaN,NaN,17.5,NaN,NaN,115.0,NaN,NaN,NaN,NaN,NaN,NaN,chrome-extension://efaidnbmnnnibpcajpcglclefin...,https://www.kedglobal.com/batteries/newsView/k...,NaN,NaN
14,ACC,France,NaN,NaN,NaN,1.5,2.0,NaN,125.0,NaN,NaN,NaN,NaN,NaN,https://www.ees-europe.com/news/european-batte...,NaN,NaN,NaN
15,Basquevolt,Spain,NaN,NaN,NaN,NaN,1.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Beyonder,Norway,NaN,NaN,NaN,10.0,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Blackstone Resources,Germany,NaN,NaN,NaN,5.0,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Blyth,United Kingdom,NaN,NaN,NaN,NaN,38.0,NaN,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Dunkirk,Norway,NaN,NaN,NaN,NaN,16.0,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Envision,China,NaN,NaN,NaN,9.0,NaN,NaN,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Envision AESC,United Kingdom,NaN,NaN,NaN,1.9,12.0,NaN,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Envision AESC,Japan,NaN,NaN,NaN,6.0,NaN,18.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Envision AESC,United States of America,NaN,NaN,NaN,3.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Envision AESC,France,NaN,NaN,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,FAAM,Italy,NaN,NaN,2.5,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Freyr,Norway,NaN,NaN,NaN,NaN,50.0,100.0,200.0,NaN,NaN,NaN,NaN,NaN,https://www.automotivelogistics.media/battery-...,https://net-zero.blog/net-zero-ninety/freyr,NaN,NaN
27,Impact,Poland,NaN,NaN,NaN,5.0,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Inobat,Slovakia,NaN,NaN,NaN,4.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Itavolt,Italy,NaN,NaN,0.0,0.0,NaN,40.0,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Laclanche,Germany,NaN,NaN,NaN,2.5,NaN,NaN,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Morrow,Norway,NaN,NaN,NaN,NaN,32.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Northvolt,Sweden,NaN,NaN,NaN,0.0,40.0,NaN,110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Northvolt,Germany,NaN,NaN,NaN,0.0,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,SCB,Switzerland,NaN,NaN,NaN,7.6,NaN,NaN,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,UK Centre of Electrification,United Kingdom,NaN,NaN,NaN,0.0,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Varta,Germany,NaN,NaN,NaN,0.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Volkswagen,Germany,NaN,NaN,NaN,0.0,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Volkswagen,Spain,NaN,NaN,NaN,0.0,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df = df.drop(columns=
             ['Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17'],
             axis=1)
df

,Manufacturer,Country,2022 (GWh),2023 (market share),2023 (GWh),2024 (GWh),2025 (GWh),2028 (GWh),2030 (GWh),2035 (GWh),2040 (GWh),2050 (GWh)
0,CATL,China,184.4,0.368,259.7,NaN,NaN,307.0,600.0,NaN,NaN,NaN
1,CATL,Germany,0.0,NaN,0.0,0.0,NaN,NaN,100.0,NaN,NaN,NaN
2,LG Chem,South Corea,NaN,NaN,NaN,NaN,260.0,NaN,NaN,NaN,NaN,NaN
3,LG Chem,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LG Chem,Poland,NaN,NaN,NaN,65.0,NaN,NaN,65.0,NaN,NaN,NaN
5,LG Chem,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,TESLA,United States of America,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
7,BYD,China,70.5,0.158,111.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Samsung SDI,China,NaN,0.038,NaN,NaN,NaN,94.0,NaN,NaN,NaN,NaN
9,Samsung SDI,Hungary,NaN,NaN,NaN,40.0,NaN,NaN,40.0,NaN,NaN,NaN
10,Panasonic,Japan,NaN,NaN,NaN,17.0,17.0,NaN,NaN,NaN,NaN,NaN
11,Panasonic,"North America, Mexico",NaN,NaN,NaN,37.0,NaN,NaN,NaN,NaN,NaN,NaN
12,SK On,South Corea,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN
13,SK On,Hungary,NaN,NaN,17.5,NaN,NaN,115.0,NaN,NaN,NaN,NaN
14,ACC,France,NaN,NaN,NaN,1.5,2.0,NaN,125.0,NaN,NaN,NaN
15,Basquevolt,Spain,NaN,NaN,NaN,NaN,1.0,10.0,NaN,NaN,NaN,NaN
16,Beyonder,Norway,NaN,NaN,NaN,10.0,NaN,NaN,10.0,NaN,NaN,NaN
17,Blackstone Resources,Germany,NaN,NaN,NaN,5.0,NaN,NaN,5.0,NaN,NaN,NaN
18,Blyth,United Kingdom,NaN,NaN,NaN,NaN,38.0,NaN,40.0,NaN,NaN,NaN
19,Dunkirk,Norway,NaN,NaN,NaN,NaN,16.0,NaN,50.0,NaN,NaN,NaN
20,Envision,China,NaN,NaN,NaN,9.0,NaN,NaN,24.0,NaN,NaN,NaN
21,Envision AESC,United Kingdom,NaN,NaN,NaN,1.9,12.0,NaN,18.0,NaN,NaN,NaN
22,Envision AESC,Japan,NaN,NaN,NaN,6.0,NaN,18.0,18.0,NaN,NaN,NaN
23,Envision AESC,United States of America,NaN,NaN,NaN,3.0,30.0,NaN,NaN,NaN,NaN,NaN
24,Envision AESC,France,NaN,NaN,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN
25,FAAM,Italy,NaN,NaN,2.5,NaN,NaN,NaN,8.0,NaN,NaN,NaN
26,Freyr,Norway,NaN,NaN,NaN,NaN,50.0,100.0,200.0,NaN,NaN,NaN
27,Impact,Poland,NaN,NaN,NaN,5.0,NaN,NaN,5.0,NaN,NaN,NaN
28,Inobat,Slovakia,NaN,NaN,NaN,4.0,10.0,NaN,NaN,NaN,NaN,NaN
29,Itavolt,Italy,NaN,NaN,0.0,0.0,NaN,40.0,45.0,NaN,NaN,NaN
30,Laclanche,Germany,NaN,NaN,NaN,2.5,NaN,NaN,2.5,NaN,NaN,NaN
31,Morrow,Norway,NaN,NaN,NaN,NaN,32.0,43.0,NaN,NaN,NaN,NaN
32,Northvolt,Sweden,NaN,NaN,NaN,0.0,40.0,NaN,110.0,NaN,NaN,NaN
33,Northvolt,Germany,NaN,NaN,NaN,0.0,NaN,NaN,60.0,NaN,NaN,NaN
34,SCB,Switzerland,NaN,NaN,NaN,7.6,NaN,NaN,7.6,NaN,NaN,NaN
35,UK Centre of Electrification,United Kingdom,NaN,NaN,NaN,0.0,NaN,NaN,60.0,NaN,NaN,NaN
36,Varta,Germany,NaN,NaN,NaN,0.0,NaN,NaN,2.0,NaN,NaN,NaN
37,Volkswagen,Germany,NaN,NaN,NaN,0.0,NaN,NaN,40.0,NaN,NaN,NaN
38,Volkswagen,Spain,NaN,NaN,NaN,0.0,NaN,NaN,40.0,NaN,NaN,NaN

In [12]:
df = df.drop('2023 (market share)', axis=1)
df

,Manufacturer,Country,2022 (GWh),2023 (GWh),2024 (GWh),2025 (GWh),2028 (GWh),2030 (GWh),2035 (GWh),2040 (GWh),2050 (GWh)
0,CATL,China,184.4,259.7,NaN,NaN,307.0,600.0,NaN,NaN,NaN
1,CATL,Germany,0.0,0.0,0.0,NaN,NaN,100.0,NaN,NaN,NaN
2,LG Chem,South Corea,NaN,NaN,NaN,260.0,NaN,NaN,NaN,NaN,NaN
3,LG Chem,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LG Chem,Poland,NaN,NaN,65.0,NaN,NaN,65.0,NaN,NaN,NaN
5,LG Chem,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,TESLA,United States of America,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
7,BYD,China,70.5,111.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Samsung SDI,China,NaN,NaN,NaN,NaN,94.0,NaN,NaN,NaN,NaN
9,Samsung SDI,Hungary,NaN,NaN,40.0,NaN,NaN,40.0,NaN,NaN,NaN
10,Panasonic,Japan,NaN,NaN,17.0,17.0,NaN,NaN,NaN,NaN,NaN
11,Panasonic,"North America, Mexico",NaN,NaN,37.0,NaN,NaN,NaN,NaN,NaN,NaN
12,SK On,South Corea,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN
13,SK On,Hungary,NaN,17.5,NaN,NaN,115.0,NaN,NaN,NaN,NaN
14,ACC,France,NaN,NaN,1.5,2.0,NaN,125.0,NaN,NaN,NaN
15,Basquevolt,Spain,NaN,NaN,NaN,1.0,10.0,NaN,NaN,NaN,NaN
16,Beyonder,Norway,NaN,NaN,10.0,NaN,NaN,10.0,NaN,NaN,NaN
17,Blackstone Resources,Germany,NaN,NaN,5.0,NaN,NaN,5.0,NaN,NaN,NaN
18,Blyth,United Kingdom,NaN,NaN,NaN,38.0,NaN,40.0,NaN,NaN,NaN
19,Dunkirk,Norway,NaN,NaN,NaN,16.0,NaN,50.0,NaN,NaN,NaN
20,Envision,China,NaN,NaN,9.0,NaN,NaN,24.0,NaN,NaN,NaN
21,Envision AESC,United Kingdom,NaN,NaN,1.9,12.0,NaN,18.0,NaN,NaN,NaN
22,Envision AESC,Japan,NaN,NaN,6.0,NaN,18.0,18.0,NaN,NaN,NaN
23,Envision AESC,United States of America,NaN,NaN,3.0,30.0,NaN,NaN,NaN,NaN,NaN
24,Envision AESC,France,NaN,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN
25,FAAM,Italy,NaN,2.5,NaN,NaN,NaN,8.0,NaN,NaN,NaN
26,Freyr,Norway,NaN,NaN,NaN,50.0,100.0,200.0,NaN,NaN,NaN
27,Impact,Poland,NaN,NaN,5.0,NaN,NaN,5.0,NaN,NaN,NaN
28,Inobat,Slovakia,NaN,NaN,4.0,10.0,NaN,NaN,NaN,NaN,NaN
29,Itavolt,Italy,NaN,0.0,0.0,NaN,40.0,45.0,NaN,NaN,NaN
30,Laclanche,Germany,NaN,NaN,2.5,NaN,NaN,2.5,NaN,NaN,NaN
31,Morrow,Norway,NaN,NaN,NaN,32.0,43.0,NaN,NaN,NaN,NaN
32,Northvolt,Sweden,NaN,NaN,0.0,40.0,NaN,110.0,NaN,NaN,NaN
33,Northvolt,Germany,NaN,NaN,0.0,NaN,NaN,60.0,NaN,NaN,NaN
34,SCB,Switzerland,NaN,NaN,7.6,NaN,NaN,7.6,NaN,NaN,NaN
35,UK Centre of Electrification,United Kingdom,NaN,NaN,0.0,NaN,NaN,60.0,NaN,NaN,NaN
36,Varta,Germany,NaN,NaN,0.0,NaN,NaN,2.0,NaN,NaN,NaN
37,Volkswagen,Germany,NaN,NaN,0.0,NaN,NaN,40.0,NaN,NaN,NaN
38,Volkswagen,Spain,NaN,NaN,0.0,NaN,NaN,40.0,NaN,NaN,NaN

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Manufacturer  39 non-null     object
 1   Country       39 non-null     object
 2   2022 (GWh)    3 non-null      float64
 3   2023 (GWh)    6 non-null      float64
 4   2024 (GWh)    23 non-null     float64
 5   2025 (GWh)    13 non-null     float64
 6   2028 (GWh)    9 non-null      float64
 7   2030 (GWh)    25 non-null     float64
 8   2035 (GWh)    0 non-null      float64
 9   2040 (GWh)    0 non-null      float64
 10  2050 (GWh)    0 non-null      float64
dtypes: float64(9), object(2)
memory usage: 3.5+ KB

In [14]:
print(df.isna().sum())

Manufacturer     0
Country          0
2022 (GWh)      36
2023 (GWh)      33
2024 (GWh)      16
2025 (GWh)      26
2028 (GWh)      30
2030 (GWh)      14
2035 (GWh)      39
2040 (GWh)      39
2050 (GWh)      39
dtype: int64

In [15]:
def convert_alpha3(df=pd.DataFrame):
    alpha3 = []
    others = []

    for land in df["Country"]:
        try:
            alpha3.append(pycountry.countries.get(name=land).alpha_3)
        except:
            others.append(land)

    # print(set(alpha3))
    # print(set(others))
    
    return alpha3, others

In [16]:
alpha3, others = convert_alpha3(df)

print(set(alpha3))
print(set(others))

{'JPN', 'CHE', 'SVK', 'CHN', 'NOR', 'GBR', 'SWE', 'DEU', 'POL', 'ESP', 'ITA', 'FRA', 'HUN'}
{'North America, Mexico', 'South Corea', 'United States of America'}

In [17]:
clean_df = df.copy()
others = []

for country in clean_df["Country"]:
    if country == "North America, Mexico":
        clean_df.replace(to_replace=country, value="United States of America", inplace=True)
    elif country == "South Corea":
        clean_df.replace(to_replace=country, value='Republic of Korea', inplace=True)
    else:
        others.append('land')

In [19]:
alpha3_clean, others_clean = convert_alpha3(clean_df)

print(set(alpha3_clean))
print(set(others_clean))

{'JPN', 'CHE', 'SVK', 'CHN', 'NOR', 'GBR', 'SWE', 'DEU', 'POL', 'ESP', 'ITA', 'FRA', 'HUN'}
{'Republic of Korea', 'United States of America'}

In [20]:
i = 0
for country in clean_df['Country']:
    if country == 'United States of America':
        clean_df.at[i, 'alpha3_code']='USA'
        i += 1
    elif country == 'Republic of Korea':
        clean_df.at[i, 'alpha3_code']='ROK'
        i += 1
    else:
        clean_df.at[i, 'alpha3_code']= str((pycountry.countries.get(name=country).alpha_3))
        i += 1

In [21]:
clean_df

,Manufacturer,Country,2022 (GWh),2023 (GWh),2024 (GWh),2025 (GWh),2028 (GWh),2030 (GWh),2035 (GWh),2040 (GWh),2050 (GWh),alpha3_code
0,CATL,China,184.4,259.7,NaN,NaN,307.0,600.0,NaN,NaN,NaN,CHN
1,CATL,Germany,0.0,0.0,0.0,NaN,NaN,100.0,NaN,NaN,NaN,DEU
2,LG Chem,Republic of Korea,NaN,NaN,NaN,260.0,NaN,NaN,NaN,NaN,NaN,ROK
3,LG Chem,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CHN
4,LG Chem,Poland,NaN,NaN,65.0,NaN,NaN,65.0,NaN,NaN,NaN,POL
5,LG Chem,United States of America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,USA
6,TESLA,United States of America,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN,USA
7,BYD,China,70.5,111.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CHN
8,Samsung SDI,China,NaN,NaN,NaN,NaN,94.0,NaN,NaN,NaN,NaN,CHN
9,Samsung SDI,Hungary,NaN,NaN,40.0,NaN,NaN,40.0,NaN,NaN,NaN,HUN
10,Panasonic,Japan,NaN,NaN,17.0,17.0,NaN,NaN,NaN,NaN,NaN,JPN
11,Panasonic,United States of America,NaN,NaN,37.0,NaN,NaN,NaN,NaN,NaN,NaN,USA
12,SK On,Republic of Korea,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,ROK
13,SK On,Hungary,NaN,17.5,NaN,NaN,115.0,NaN,NaN,NaN,NaN,HUN
14,ACC,France,NaN,NaN,1.5,2.0,NaN,125.0,NaN,NaN,NaN,FRA
15,Basquevolt,Spain,NaN,NaN,NaN,1.0,10.0,NaN,NaN,NaN,NaN,ESP
16,Beyonder,Norway,NaN,NaN,10.0,NaN,NaN,10.0,NaN,NaN,NaN,NOR
17,Blackstone Resources,Germany,NaN,NaN,5.0,NaN,NaN,5.0,NaN,NaN,NaN,DEU
18,Blyth,United Kingdom,NaN,NaN,NaN,38.0,NaN,40.0,NaN,NaN,NaN,GBR
19,Dunkirk,Norway,NaN,NaN,NaN,16.0,NaN,50.0,NaN,NaN,NaN,NOR
20,Envision,China,NaN,NaN,9.0,NaN,NaN,24.0,NaN,NaN,NaN,CHN
21,Envision AESC,United Kingdom,NaN,NaN,1.9,12.0,NaN,18.0,NaN,NaN,NaN,GBR
22,Envision AESC,Japan,NaN,NaN,6.0,NaN,18.0,18.0,NaN,NaN,NaN,JPN
23,Envision AESC,United States of America,NaN,NaN,3.0,30.0,NaN,NaN,NaN,NaN,NaN,USA
24,Envision AESC,France,NaN,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN,FRA
25,FAAM,Italy,NaN,2.5,NaN,NaN,NaN,8.0,NaN,NaN,NaN,ITA
26,Freyr,Norway,NaN,NaN,NaN,50.0,100.0,200.0,NaN,NaN,NaN,NOR
27,Impact,Poland,NaN,NaN,5.0,NaN,NaN,5.0,NaN,NaN,NaN,POL
28,Inobat,Slovakia,NaN,NaN,4.0,10.0,NaN,NaN,NaN,NaN,NaN,SVK
29,Itavolt,Italy,NaN,0.0,0.0,NaN,40.0,45.0,NaN,NaN,NaN,ITA
30,Laclanche,Germany,NaN,NaN,2.5,NaN,NaN,2.5,NaN,NaN,NaN,DEU
31,Morrow,Norway,NaN,NaN,NaN,32.0,43.0,NaN,NaN,NaN,NaN,NOR
32,Northvolt,Sweden,NaN,NaN,0.0,40.0,NaN,110.0,NaN,NaN,NaN,SWE
33,Northvolt,Germany,NaN,NaN,0.0,NaN,NaN,60.0,NaN,NaN,NaN,DEU
34,SCB,Switzerland,NaN,NaN,7.6,NaN,NaN,7.6,NaN,NaN,NaN,CHE
35,UK Centre of Electrification,United Kingdom,NaN,NaN,0.0,NaN,NaN,60.0,NaN,NaN,NaN,GBR
36,Varta,Germany,NaN,NaN,0.0,NaN,NaN,2.0,NaN,NaN,NaN,DEU
37,Volkswagen,Germany,NaN,NaN,0.0,NaN,NaN,40.0,NaN,NaN,NaN,DEU
38,Volkswagen,Spain,NaN,NaN,0.0,NaN,NaN,40.0,NaN,NaN,NaN,ESP

In [24]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Manufacturer  39 non-null     object
 1   Country       39 non-null     object
 2   2022 (GWh)    3 non-null      float64
 3   2023 (GWh)    6 non-null      float64
 4   2024 (GWh)    23 non-null     float64
 5   2025 (GWh)    13 non-null     float64
 6   2028 (GWh)    9 non-null      float64
 7   2030 (GWh)    25 non-null     float64
 8   2035 (GWh)    0 non-null      float64
 9   2040 (GWh)    0 non-null      float64
 10  2050 (GWh)    0 non-null      float64
 11  alpha3_code   39 non-null     object
dtypes: float64(9), object(3)
memory usage: 3.8+ KB

In [25]:
clean_df.describe()

,2022 (GWh),2023 (GWh),2024 (GWh),2025 (GWh),2028 (GWh),2030 (GWh),2035 (GWh),2040 (GWh),2050 (GWh)
count,3.000000,6.000000,23.000000,13.000000,9.000000,25.000000,0.0,0.0,0.0
mean,84.966667,65.183333,9.326087,46.769231,83.000000,68.204000,NaN,NaN,NaN
std,93.047318,104.568971,16.298946,69.177494,92.589146,120.101757,NaN,NaN,NaN
min,0.000000,0.000000,0.000000,1.000000,10.000000,2.000000,NaN,NaN,NaN
25%,35.250000,0.625000,0.000000,12.000000,20.000000,10.000000,NaN,NaN,NaN
50%,70.500000,10.000000,3.000000,30.000000,43.000000,40.000000,NaN,NaN,NaN
75%,127.450000,87.925000,8.300000,40.000000,100.000000,60.000000,NaN,NaN,NaN
max,184.400000,259.700000,65.000000,260.000000,307.000000,600.000000,NaN,NaN,NaN

In [23]:
clean_df.to_csv('CountryComp_clean_alpha3.csv')